#server:
#  port: 9090

spring:
  application:
    name: msvc-countAndMovement
  #  datasource:
  #    driver-class-name: org.postgresql.Driver
  #    url: jdbc:postgresql://localhost:5432/coursesDb
  ##    driver-class-name: com.mysql.cj.jdbc.Driver
  ##    url: jdbc:mysql://localhost:3306/coursesDb
  #    username: xxharutoxx
  #    password: dell@190
  #  jpa:
  #    hibernate:
  #      ddl-auto: create
  #    database: postgresql
  #    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #Para poner correr sin haber configurado el CONFIG SERVER (OPCIONAL)
  config:
    import: optional:configserver:http://localhost:8888

#Configuracion para que el mcvs de student se registre en EUREKA
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZOne: http://localhost:8761/eureka
