eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  #  config:
  #    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: clientAndPerson
          uri: http://localhost:9090
          predicates:
            - Path=/api/clientAndPerson/**
        - id: countAndMovement
          uri: http://localhost:8090
          predicates:
            - Path=/api/countAndMovement/**