server:
  port: 9090

spring:
  application:
    name: msvc-clientAndPerson
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clientAndPerson
    username: xxharutoxx
    password: dell@190
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  #Para poner correr sin haber configurado el CONFIG SERVER (OPCIONAL)
#  config:
#    import: optional:configserver:http://localhost:8888

#Configuracion para que el mcvs de student se registre en EUREKA
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZOne: http://localhost:8761/eureka